openapi: 3.0.0
info:
  title: Todo Chatbot API
  version: 1.0.0
  description: API for managing Todo items and user authentication for the Todo Chatbot application.
servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
paths:
  /users/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
              properties:
                username:
                  type: string
                  example: johndoe
                email:
                  type: string
                  format: email
                  example: john.doe@example.com
                password:
                  type: string
                  format: password
                  example: securepassword123
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input or user already exists
  /users/login:
    post:
      summary: Authenticate a user and get a token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: john.doe@example.com
                password:
                  type: string
                  format: password
                  example: securepassword123
      responses:
        '200':
          description: User authenticated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: Authentication token
        '401':
          description: Invalid credentials
  /users/me:
    get:
      summary: Get current user's profile
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Current user profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
  /todos:
    post:
      summary: Create a new todo item
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoItemCreate'
      responses:
        '201':
          description: Todo item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
    get:
      summary: Get all todo items for the authenticated user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of todo items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoItem'
        '401':
          description: Unauthorized
  /todos/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: ID of the todo item
        schema:
          type: string
          format: uuid
    get:
      summary: Get a specific todo item by ID
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Todo item details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
        '401':
          description: Unauthorized
        '404':
          description: Todo item not found or not owned by user
    put:
      summary: Update a specific todo item by ID
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoItemUpdate'
      responses:
        '200':
          description: Todo item updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Todo item not found or not owned by user
    delete:
      summary: Delete a specific todo item by ID
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Todo item deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Todo item not found or not owned by user
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        username:
          type: string
        email:
          type: string
          format: email
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
    TodoItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        userId:
          type: string
          format: uuid
          readOnly: true
        title:
          type: string
        description:
          type: string
          nullable: true
        status:
          type: string
          enum: [pending, completed, in progress]
        dueDate:
          type: string
          format: date
          nullable: true
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
    TodoItemCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
        description:
          type: string
          nullable: true
        status:
          type: string
          enum: [pending, completed, in progress]
          default: pending
        dueDate:
          type: string
          format: date
          nullable: true
    TodoItemUpdate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
          nullable: true
        status:
          type: string
          enum: [pending, completed, in progress]
        dueDate:
          type: string
          format: date
          nullable: true